### ISSUE TITLE
does not load bmp

### ISSUE THREAD

**Issue by revast** [MizunagiKB/potrace_gui#1]
Traceback (most recent call last):
  File "./potrace_gui.py", line 304, in actionFileOpen
    self.m_oCViewSVG.open(svg_file.fileName())
  File "./potrace_gui.py", line 105, in open
    shell=False
  File "/usr/lib/python3.6/subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1344, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: ''

note that I opened a bmp from home directory...

**Comment by MizunagiKB** [comment]
1) Toggle button
  Although it is not expected function, I tried to be able to check before and after conversion.
2) Quick Convert
  Then I tried to convert multiple files at once.

![testimage](https://user-images.githubusercontent.com/5047878/46148340-cfb47200-c2a2-11e8-945b-2100447e3016.jpg)
